name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checckout@v2 # pega os dados e baixa no host ubuntu
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go